### ISSUE TITLE
Fontsize Amount

### ISSUE THREAD

**Issue by bhuko** [manuelbl/SwissQRBill.NET#13]
I guess the font size of Amount should be same as other text, or?
BillLayout.cs about line 177   graphics.PutText(_amount, currencyWidthPp, y, _labelFontSize, false);
-> _textFontSize

Did some testing with with the library ... makes to me a very good impression ... everything works as expected so far
... I learned quite few things about good coding und pdf generation..
Thank you very much

**Comment by manuelbl** [comment]
Thanks for pointing this out. This indeed looks like a bug. I'll fix it soon.

**Comment by manuelbl** [comment]
It has been fixed in release 2.3.1.
