### ISSUE TITLE
French and italian translations

### ISSUE THREAD

**Issue by gmertenat** [manuelbl/SwissQRBill.NET#14]
According to the "Swiss Implementation Guidelines QR-bill" (Annex D: Multilingual glossary), the french value for the key "PaymentPart" should be "Section paiement" (instead of "Section de paiement"), and the italian value should be "Sezione pagamento" (instead of "Sezione di pagamento").

https://www.paymentstandards.ch/dam/downloads/ig-qr-bill-en.pdf

**Comment by manuelbl** [comment]
Thanks for pointing this out. I'll fix it.

**Comment by manuelbl** [comment]
Fixed in release 2.3.3
