### ISSUE TITLE
PNG support missing

### ISSUE THREAD

**Issue by nils-thomann** [manuelbl/SwissQRBill.NET#15]
According to the README file PNG is supported. Unfortunately I can't find the method to create a PNG file. Shouldn't there be a PNG flag in the GraphicsFormat enum?

**Comment by manuelbl** [comment]
The use of PNG requires that a pixel resolution is chosen. And the standard mandates the use of vector graphics - making the use of PNG sort of illegal. For those reasons, it's not directly available in *GraphicsFormat*.

Yet, the required *PNGCanvas* is part of the library. Please have a look at https://github.com/manuelbl/SwissQRBill.NET/tree/master/Examples/PNGGeneration for how to use it.

**Comment by manuelbl** [comment]
Now available with a simpler interface in *master* branch.
