### ISSUE TITLE
Corner marks and scissor

### ISSUE THREAD

**Issue by csillikd** [manuelbl/SwissQRBill.NET#2]
There are published images for the scissor and the corner marks, see that:
[https://www.paymentstandards.ch/de/shared/communication-grid/eckmarken.html](https://www.paymentstandards.ch/de/shared/communication-grid/eckmarken.html)
And for the swiss cross too:
[https://www.paymentstandards.ch/de/shared/communication-grid/swiss-qr-code.html]https://www.paymentstandards.ch/de/shared/communication-grid/swiss-qr-code.html
Otherwise great job!

**Comment by manuelbl** [comment]
I am aware of the images provided by SIX. What would be the advantage of using them?

Even though this library's implementation is different, the corner marks and the Swiss cross should look exactly the same (the padding around the Swiss cross can be somewhat bigger as this library extends it to cover entire QR code pixels). The scissors are different - but are they inferior?

**Comment by csillikd** [comment]
Advantages:
-they do not look like the same, but they are exactly the same
-easier to change or extend
Yes, they are inferior. Such small things make the difference between ok and perfect.

**Comment by manuelbl** [comment]
The images from SIX are a mess. The specification says to use a line width of 0.75pt for the corner marks but their images use 0.8pt. And in the SVG files, the lines don't even properly align in the corners:

<img alt="corner marks" src="https://user-images.githubusercontent.com/10954524/72784593-73a8f600-3c29-11ea-96f6-8cdfa9f6ce1b.png" width="30%">

The images for the scisscors are even worse:

The Adobe Illustrator version basically consists of text element with the scissors symbol from the Zapf Dingbats font, which isn't available on all platforms.

The EPS version is a convulted nightmare of more than 2.5 MB of size.

The SVG version contains both a pixel image of the scissors and a text element with the scissors symbol from the Zapf Dingbats font. Additionally, it would likely fall back to the [Unicode Black Scissors](https://www.compart.com/en/unicode/U+2702) as they character code matches. What the Unicode scissors look like depends on the platform and the font. So unsurprisingly, the same SVG has very different scissors when opened on different platforms and with different software.

So which of the scissors symbols are you refering to? The pixel image? The Zapf Dingbats versoin? The Unicode version (what platform, what font)?

**Comment by manuelbl** [comment]
Release 2.2 now adds dashed and dotted lines (with and without scissors) to separate the bill from the rest of the document, and the payment part from the receipt.
