### ISSUE TITLE
Swico invoice information - format of invoice date

### ISSUE THREAD

**Issue by mikehachen** [manuelbl/SwissQRBill.NET#24]
Hi there
According to the [syntax definition version 1.2)](https://www.swiss-qr-invoice.org/downloads/qr-bill-s1-syntax-de.pdf) dates have to be formatted like yymmdd (year, month, day). In practice I found quite a lot of invoices with dates formatted like yymmddhhmmss (year, month, day, hour, minute, second). 
I could create a pull request so that both formats are accepted and parsed correctly. But before I do the work, I wanted to ask if such a pull request would be accepted at all.

BTW: Thank you for the great library!
Michael

**Comment by manuelbl** [comment]
The goal of the library is to be rather tolerant when processing input. So allowing several date formats make sense.

Therefore I'd gladly accept a PR.
