### ISSUE TITLE
Vertikale Perforationslinie

### ISSUE THREAD

**Issue by mikekaufmann** [manuelbl/SwissQRBill.NET#26]
Ist es möglich, die vertikale Perforationslinie nicht zu zeichnen?

Hintergrund: Kunde hat bereits performiertes Papier

**Comment by manuelbl** [comment]
Es ist möglich mit dem `SeparatorType` Property zu steuern, ob und welche Art von Linien gezeichnet wird.

```c#
Bill bill = new Bill
{
    ....
    Format =
    {
        SeparatorType = SeparatorType.None
    }
}
```

Passt einer der Enum-Werte (siehe [Enum SeparatorType](https://codecrete.net/SwissQRBill.NET/api/Codecrete.SwissQRBill.Generator.SeparatorType.html))?

**Comment by mikekaufmann** [comment]
Herzlichen Dank-  das funktioniert wunderbar!

Ein wenig wiedersprüchlich finde ich das im Zusammenhang mit dem Enum **OutputSize**:
- Für was wird die Unterscheidung _QrBillOnly_ und _QrBillWithHorizontalLine_ benötigt, wenn über das Property _SeparatorType_ gesteuert werden kann, ob und wie die Perforationslinien gezeichnet werden soll?
- Um durchgängig zu sein, müsste es bei diesem Anssatz eigentlich auch anstatt des Enum-Werts _A4PortraitSheet_ die zwei Enum-Werte _A4PortraitSheetQrBillOnly_ und _A4PortraitSheetQrBillWithHorizontalLine_ geben

Es gibt wohl in der Praxis nur die Unterscheidung mit/ohne Perforationslinien. Abhängig davon, ob auf perforiertes Papier gedruckt wird oder nicht. Aus meiner Sicht sollte der Enum _OutputSize_ deshalb nur aus den Werten _A4PortraitSheet_, _QrBillOnly_ und _QrCodeOnly_ bestehen. Das Zeichnen der Perforationslinien wird über das Property _SeparatorType_ gesteuert.

Sollte es in der Praxis auch den Fall geben, dass das Zeichnen der beiden Perforationslinien unterschieden werden muss, müsste es wohl anstelle der Eigenschaft _SeperatorType_ die beiden Eigenschaften _SeparatorTypeHorizontal_ und _SeparatorTypeVertical_ geben.

**Comment by manuelbl** [comment]
Die Option *QrBillWithHorizontalLine* wurde eingeführt, damit in einer Reporting-/Output Management-Software eine QR-Rechnung mit Linien hinzugefügt werden kann, ohne die ganze A4-Seite zu überdecken. Zwar wäre der Seiteninhalt mit *A4PortraitSheet* immer noch sichtbar, da QR-Rechnung keinen weissen Hintergrund hat. Aber im Design-Modus der Software wird die Arbeit mit dem A4-Platzhalter für die QR-Rechnung sehr mühsam.

Die Option *QrBillOnly* genügt in diesem Fall nicht. Denn die Linie und die Schere liegen genau auf dem Rand der 105 mm x 210 mm Fläche, so dass die halbe Linie und vor allem die halbe Schere abgeschnitten wird. *QrBillWithHorizontalLine* bietet also zusätzliche 5mm, um alles sauber darzustellen.

Ich sehe aber, dass es zu Verwirrung führt. Der Name ist unglücklich. Ich werde ihn bei Gelegenheit anpassen und auch die Beschreibung verbessern.

**Comment by mikekaufmann** [comment]
Besten Dank für die Erläuterungen!

Vielleicht sehe ich zu wenig dahinter. Naiv hätte ich gesagt, dass bei OutputSize=_QRBillOnly_ und bei einer zusätzlich gewünschten horizontalen Linie (definiert via Eigenschaft _SeparatorType_ bzw. _SeparatorTypeHorizontal_) einfach die 5mm mehr eingerechnet werden müssen => 110mm x 210mm. 

Ist SeparatorType=_SeparatorType.None_, so reichen die 105mm x 210mm.

**Comment by manuelbl** [comment]
Die Ausgabegrösse *QrBillWithHorizontalLine* ist nun zu *QrBillExtraSpace* umbenannt worden (mit Rückwärtskompatibilität) und die Beschreibung ist verbessert.

Siehe Version 2.5.0.
