### ISSUE TITLE
Scan mit PostFinance App

### ISSUE THREAD

**Issue by christophbrunner** [manuelbl/SwissQRBill.NET#28]
Wenn man mit der PostFinance App die QR-Rechnungen scannt, kommt bei diversen Rechnungen mit Type QRR ein Error.
So auch mit dem Beispiel  [Example 4: Debtor to be filled in, in German](https://github.com/manuelbl/SwissQRBill/wiki/Swiss-QR-Invoice-Examples).

Wir da etwas falsch generiert? Oder ist das möglicherweise ein Bug in der PostFinance App? Mit der Raiffeisen App klappt es prima.

**Comment by manuelbl** [comment]
Das Beispiel 4 wird vom SIX Validierungsportal (
https://validation.iso-payments.ch/gp/qrrechnung/home) als gültig
eingestuft. Es ist allerdings denkbar, dass die PostFinance App eine
detaillierte Prüfung durchführt und erkennt, dass das Konto nicht
existiert. Die Kontonummer ist formal gültig, aber frei erfunden.

Ich habe kein PF-Konto und kann die App nicht testen. Deshalb weiss ich
auch nicht, was die Fehlermeldung ist, und kann nur spekulieren.

**Comment by mikehachen** [comment]
Ich hab das Beispiel 4 im Validierungsportal der Postfinance geprüft, es wird als korrekt erkannt. Die QR-Rechnung ist also korrekt.
15/09/2020 11.22.11     Protokoll
================================================================================
    Datei:  qr-invoice-e6.pdf.xml
    Typ:    QR-Rechnung
    --------------------------------------------------------------------
    Ergebnis:
        Datei ist in ihrem Aufbau korrekt, aber es gibt Warnungen oder Hinweise.
        Fehler:    0
        Warnungen: 0
        Hinweise:  1

    Hinweise
    --------------------------------------------------------------------
    Hinweis zum Aufbau des QR-Code-Datenelements /QRCH/CcyAmt/Amt
    Hinweis:
        Es wurde kein Wert in Amount angegeben. Für die Weiterverarbeitung auf der Testplattform wird ein Amount zwingend benötigt 
        und mit dem Wert '1.00' simuliert. Im Schweizer Implementation Guidelines QR-Rechnung ist der Amount optional.
    Dateiposition:
        Zeile:  30
        Spalte: 13
================================================================================
15/09/2020 11.22.11     Protokoll
================================================================================
    Datei:  conv/CSV_QRR_20200915112211.csv
    Typ:    ESR/ASR/ES/QRR
    --------------------------------------------------------------------
    Ergebnis:
        Datei ist in ihrem Aufbau korrekt.
================================================================================
