### ISSUE TITLE
Image quality

### ISSUE THREAD

**Issue by Netclick19** [manuelbl/SwissQRBill.NET#29]
Hi,
first I want to say thank you for your job. It's excellent and very useful!

I've a question about the image quality, is it possible to set the quality of png image generated?
My image is a little bit low quality when I generate it.

Thank you for your support.

**Comment by manuelbl** [comment]
With *quality* you probably mean the resolution. Yes, that can be controlled:

```
            Bill bill = new Bill
            {
                ...
                Format = new BillFormat {
                    Resolution = 600
                }
            };
```

**Comment by Netclick19** [comment]
Yes, sorry. I meant resolution.
Thank you for your answer.
