### ISSUE TITLE
Zeilenumbruch in Zusätzliche Informationen

### ISSUE THREAD

**Issue by webunitysystems** [manuelbl/SwissQRBill.NET#32]
Würde ein (forcierter) Zeilenumbruch im Feld "Zusätzliche Informationen" gegen die Spezifikation verstossen?

**Comment by manuelbl** [comment]
Der Standard sieht keine Zeilenumbrüche innerhalb eines Datenfelds vor. Sie werden bereits als Trenner zwischen den Feldern genützt und es gibt keine Methode (z.B. Escaping), um sie innerhalb eines Felds unterzubringen.

Die Library ersetzt Zeilenumbrüche automatisch durch einen Leerschlag und zeigt dies bei der Validierung mit einer Warnung an.
