### ISSUE TITLE
Graphics format PNG not available

### ISSUE THREAD

**Issue by Netclick19** [manuelbl/SwissQRBill.NET#40]
Hi,

I've a working .net 4.8 project that generates QR bill with Codecrete.SwissQRBill.Generator 2.5.3 version.
I've tryed to update to 3.0.0 version but I got this exception.
Graphics format PNG not available (are you missing the NuGet package Codecrete.SwissQRBill.Generator?)
I've this packages installed:
Codecrete.SwissQRBill.Generator 3.0.0 and Net.Codecrete.QrCodeGenerator 2.0.1
Try to with Codecrete.SwissQRBill.Core 3.0.0 (same result)

What I have to do to get the last version working?

Kind regards.

**Comment by manuelbl** [comment]
Thanks for reporting the issue. I can reproduce it.

I will investigate it further and hopefully soon publish a fixed version.

**Comment by chaelli** [comment]
same issue on .net core 6. btw - thanks for the library!

**Comment by manuelbl** [comment]
Release 3.0.1 has been published. It addresses this issue.

**Comment by chaelli** [comment]
solved it for me - thanks

**Comment by Netclick19** [comment]
Solved it for me too.
Thank you for your well job!
