### ISSUE TITLE
Das Element 'StrdBkgInf' darf nur geliefert werden, wenn es auch befüllt ist

### ISSUE THREAD

**Issue by mikekaufmann** [manuelbl/SwissQRBill.NET#44]
Bei einem Kunden ist die Version 2.5.2.0 des SwissQRBill.NET Generators in Verwendung.
Erzeugt er eine QR-Rechnung und prüft die Rechnung danach mit der Testplattform von PostFinance, erhält er jeweils den folgenden Hinweis:

Zeile;Datenelement;Meldungsart;Meldungstext
32;Rechnungsinformationen;Hinweis;Das Element 'StrdBkgInf' darf nur geliefert werden, wenn es auch befüllt ist.

Die Rechnungsinformationen bzw. Bill.BillInformation wird beim Erstellen der QR-Rechnung nicht befüllt. 
Es ist aber nicht null zugewiesen, sondern ein leerer String.

Ist dieser Fehler bekannt und in einer aktuelleren Version behoben?

**Comment by manuelbl** [comment]
Das ist in Version 3 korrigiert.

Es geht im Wesentlichen auf einen Fehler in der ursprünglichen Spezifikation zurück, wo etwas anders beschrieben war, als es beabsichtigt war. Unterdessen ist die Spezifikation geändert worden.

Die Meldung der Testplattform ist aber nur ein Hinweis, kein Fehler. Die QR-Rechnung wird trotzdem überall akzeptiert.

**Comment by mikekaufmann** [comment]
Alles klar! Danke für die Antwort und für den tollen Job :)
