### ISSUE TITLE
Visuelle Kontrolle - QR-Code ausserhalb Rahmen

### ISSUE THREAD

**Issue by mikekaufmann** [manuelbl/SwissQRBill.NET#5]
Hallo
Auf der [Testplattform von PostFinance](https://testplattform.postfinance.ch) gibt es eine visuelle Kontrolle. Im Anhang ist das Resultat der Prüfung einer QR-Rechnung zu finden, welche ich mit SwissQRBill.NET erstellt habe. Der QR-Code liegt ausserhalb des vorgegebenen Rahmens. Ist das ein Fehler bzw. ein Problem?

Besten Dank für ein Feedback!

[QR-Rechnung mit QR-Referenz_Visuelle_Kontrolle.pdf](https://github.com/manuelbl/SwissQRBill.NET/files/4292079/QR-Rechnung.mit.QR-Referenz_Visuelle_Kontrolle.pdf)

**Comment by manuelbl** [comment]
Vielen Dank für den Input. Diese Testplattform kannte ich noch nicht.

Ich werde es prüfen und wahrscheinlich korrigieren.

**Comment by manuelbl** [comment]
Korrigiert und in Release 2.2.1 veröffentlicht.
