### ISSUE TITLE
OutputSize "QrBillExtraSpace" is not high enough

### ISSUE THREAD

**Issue by lump-dev** [manuelbl/SwissQRBill.NET#50]
Dear Manuel

The scissors are truncated and it has no separator line (see screenshot)

Format:
{
	"Format": {
		"Language": "DE",
		"OutputSize": "**QrBillExtraSpace**",
		"FontFamily": "Arial",
		"SeparatorType": "SolidLineWithScissors",
		"FileType": "png"
	},
...
}

<img width="893" alt="QRBill_Sample_Screenshot" src="https://user-images.githubusercontent.com/49945044/166425654-1b288b1c-3c3c-456a-8815-4011ff40c999.png">

Thank you for your support.

Kind regards
Raphae

l

**Comment by manuelbl** [comment]
Can you show your code? It looks as if you are using the library in a way where the PNG size is determined in another way.

**Comment by lump-dev** [comment]
Thanks for your hint. I have found the reason for the issue.

I changed the height and width with the correct constants.

`PNGCanvas canvas = new PNGCanvas(QRBill.QrBillWithHoriLineWidth, QRBill.QrBillWithHoriLineHeight, bill.Format.Resolution, bill.Format.FontFamily)`
