### ISSUE TITLE
Perforation bei OutputSize.QrBillOnly

### ISSUE THREAD

**Issue by mikekaufmann** [manuelbl/SwissQRBill.NET#6]
Wenn die QR-Rechnung mit _OutputSize.A4PortraitSheet_ gezeichnet wird, erscheint sowohl oberhalb als auch zwischen Empfangsschein und Zahlteil eine gestrichelte Linie mit Scherensymbol. Wird die QR-Rechnung mit _OutputSize.QrBillOnly_ gezeichnet, erscheint die Perforation nur zwischen Empfangsschein und Zahlteil aber nicht oberhalb der beiden Elemente. Gibt es eine Möglichkeit die Ausgabe der Perforation zu steuern, damit sie auch bei _OutputSize.QrBillOnly_ oberhalb der Elemente Empfangsschein und Zahlteil gezeichnet wird?

P.S. Herzlichen Dank für die Korrektur in V2.2.1 :)

**Comment by manuelbl** [comment]
Das gibt es genau so noch nicht.

Was ist der Use Case? Soll die QR-Rechnung auf eine A4-Seite hinzugefügt werden, die noch weitere Infos (z.B. die eigentliche Rechnung) enthält? Falls ja, ist es möglich, *OutputSize.A4PortraitSheet* zu verwenden. Dann werden beide Perforationslinien gezeichnet. Der Teil oberhalb der QR-Rechnung bleibt erhalten, und wird nicht durch einen weissen HIntergrund oder ähnliches überdeckt.

**Comment by mikekaufmann** [comment]
Wir nutzen [Active Reports](https://www.grapecity.com/activereports) als Reporting Tool. Ich wollte die QR-Rechnung als Sub-Report erstellen, damit ich sie sowohl auf der Rechnung direkt, als auch auf einem separaten Zusatzblatt verwenden kann. Ich habe dazu ein Picture-Control auf dem Sub-Report platziert und weise diesem die QR-Rechnung zu, welche ich mit _OutputSize.QrBillOnly_ gezeichnet habe, zu. 

Für das Zusatzblatt habe ich eine einfache Lösungen gefunden:
1. QR-Rechnung mit _OutputSize.A4PortraitSheet_ erzeugen
2. Die erzeugte QR-Rechnung als Wasserzeichen des Berichts definieren
3. Weitere Infos oberhalb der QR-Rechnung ausgeben

Bei der Ausgabe auf der eigentlichen Rechnung taugt dieser Ansatz aber leider nicht, da einige Kunden ihr Briefpapier als Wasserzeichen auf dem Report hinterlegt haben.

Wie könnte ich das umsetzen? Idee?

**Comment by manuelbl** [comment]
Ich verstehe den Use. Das ist so noch nicht machbar.

Ich überlege, welche Erweiterung geeignet wäre, das abzudecken. Es genügt nicht, die Perforationslinie und die Schere zu zeichnen, da in Kombination mit *OutputSize.QrBillOnly* die halbe Schere und die halbe Linie ausserhalb des Zeichenbereichs liegt und also nicht sichtbar wäre. Wahrescheinlich ist eine zusätzliche *OutputSize* nötig, die 107 oder 108mm hoch ist.

**Comment by mikekaufmann** [comment]
Ich wäre sehr froh, wenn das so möglich wäre. Andernfalls muss ich die Perforationslinie und die Schere selber zeichnen bzw. als Graphik einfügen. Wäre aber doch ziemlich unschön. 
Besten Dank für die Erweiterung!

**Comment by manuelbl** [comment]
Eine Lösung ist bereits in Arbeit...

**Comment by mikekaufmann** [comment]
Funktioniert perfekt - besten Dank!
