### ISSUE TITLE
Adding the possibility to have 3 address lines

### ISSUE THREAD

**Issue by marom17** [manuelbl/SwissQRBill.NET#60]
Actually it's impossible to have address with 3 lines. The insurances use some time this.
Example:
HELVETIA PATRIA ASSURANCES
RUE DENT-BLANCHE 20
CASE POSTALE 717
1950 Sion

We have some client that can't send the bills because the address on the QRCode is incorrect.

**Comment by manuelbl** [comment]
The number of address lines is given by the Swiss QR bill standard. It cannot be changed without going through the lengthy process of evolving the standard and giving all involved parties ample time to prepare for a new version of the standard. You are welcome to initiate this process.

The number of address lines is limited in the QR bill payment slip. But this address is only used to make a payment. And the recipient of the invoice is actually the sender of the payment. So he won't even use the address for the payment. Instead he will just select a bank account to pay from.

The postal address for physically sending the invoice is either at the top of the A4 sheet or on a separate sheet, and possibly on the envelope. So it can be different from the address on the payment slip even though it's the same party.

I understand it would be easier to have an identical address in both places. But we have to deal with the restrictions of the standard for now.

**Comment by marom17** [comment]
Thank you very much for your answer. We will inform our client and see if they want to initiate the procedure to improve the standard.
