### ISSUE TITLE
QrCodeOnly with quiet zone

### ISSUE THREAD

**Issue by EnraH** [manuelbl/SwissQRBill.NET#61]
Is it possible to generate a QrCode (QrCodeOnly without the entire payment slip) that has a quite zone (white margin) around it? If not, would it be possible to add such a feature?

**Comment by manuelbl** [comment]
You can generate the QR code only, but it indeed has no quite zone.

Can you describe the use case in more detail? In what context will the QR code be used? What graphics format are you using?

**Comment by manuelbl** [comment]
This might be a valuable addition. How big should the quite zone be? I'm considering several options:

1. Minimum as required by standard, i.e. a width of four modules (modules are the "pixels" of a QR code). Thus the effective width would depend on the QR code content: longer content -> smaller modules -> smaller quiet zone.
2. Fixed width of 5mm: A fixed width is visually more consistent. 5mm will always be sufficient.
3. Configurable width: The width can be configured but is independent of the module size.

I'm leaning towards option 2 as it visually consistent and doesn't need additional configuration (which increases complexity for users of the library).

**Comment by EnraH** [comment]
Your considerations sounds reasonable to me. If configurability is regarded as useful, it may still be added later on.

**Comment by manuelbl** [comment]
A new output size has been added in version 3.0.6: `QrCodeWithQuietZone`

See https://codecrete.net/SwissQRBill.NET/api/Codecrete.SwissQRBill.Generator.OutputSize.html#fields

**Comment by EnraH** [comment]
Thank you very much for the prompt implementation.
