### ISSUE TITLE
Package-install fails for .NET Fx 4.6.2 -> 4.8

### ISSUE THREAD

**Issue by zaengi** [manuelbl/SwissQRBill.NET#62]
Hello,
according to every SPEC, your nuget should be compatible, but it doesnt install in PM console:

PM> NuGet\Install-Package Codecrete.SwissQRBill.Core -Version 3.0.6
Installing 'Codecrete.SwissQRBill.Core 3.0.6'.
Successfully installed 'Codecrete.SwissQRBill.Core 3.0.6'.
Adding 'Codecrete.SwissQRBill.Core 3.0.6' to SwissQR.
Uninstalling 'Codecrete.SwissQRBill.Core 3.0.6'.
Successfully uninstalled 'Codecrete.SwissQRBill.Core 3.0.6'.
Install failed. Rolling back...
**NuGet\Install-Package : Could not install package 'Codecrete.SwissQRBill.Core 3.0.6'. You are trying to install this package into a project that _targets '.NETFramework,Version=v4.6.2',_ but the package does not contain any 
assembly references or content files that are compatible with that framework. For more information, contact the package author.**
At line:1 char:1
+ NuGet\Install-Package Codecrete.SwissQRBill.Core -Version 3.0.6
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by manuelbl** [comment]
I'm afraid I can't reproduce it. I've tested it with two .NET Framework 4.6.1 projects and it works without problems:

```
PM> NuGet\Install-Package Codecrete.SwissQRBill.Core -Version 3.0.6


Attempting to gather dependency information for package 'Codecrete.SwissQRBill.Core.3.0.6' with respect to project 'Test-Project', targeting '.NETFramework,Version=v4.6.1'
Gathering dependency information took 9 ms
Attempting to resolve dependencies for package 'Codecrete.SwissQRBill.Core.3.0.6' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Codecrete.SwissQRBill.Core.3.0.6'
Resolved actions to install package 'Codecrete.SwissQRBill.Core.3.0.6'
Retrieving package 'Codecrete.SwissQRBill.Core 3.0.6' from 'nuget.org'.
Retrieving package 'Net.Codecrete.QrCodeGenerator 2.0.0' from 'nuget.org'.
Adding package 'Net.Codecrete.QrCodeGenerator.2.0.0' to folder 'C:\Users\Me\Documents\Test-Project\packages'
Added package 'Net.Codecrete.QrCodeGenerator.2.0.0' to folder 'C:\Users\Me\Documents\Test-Project\packages'
Added package 'Net.Codecrete.QrCodeGenerator.2.0.0' to 'packages.config'
Successfully installed 'Net.Codecrete.QrCodeGenerator 2.0.0' to Test-Project
Adding package 'Codecrete.SwissQRBill.Core.3.0.6' to folder 'C:\Users\Me\Documents\Test-Project\packages'
Added package 'Codecrete.SwissQRBill.Core.3.0.6' to folder 'C:\Users\Me\Documents\Test-Project\packages'
Added package 'Codecrete.SwissQRBill.Core.3.0.6' to 'packages.config'
Successfully installed 'Codecrete.SwissQRBill.Core 3.0.6' to Test-Project
Executing nuget actions took 751 ms
Time Elapsed: 00:00:00.7978289
PM> 
```

Can you provide more information about your project? Is it a UI application, a console application or a class library? Are you using WinForms, WPF, ASP.NET? Does your project contain a `packages.config` file? What IDE and what version of IDE are you using? etc.
