### ISSUE TITLE
How should NoRef payment slips be generated?

### ISSUE THREAD

**Issue by axelgenus** [manuelbl/SwissQRBill.NET#67]
I am struggling a bit to generate "not for payment" slips. The validator triggers errors however I configure the bill:

1) Setting both Account and Reference properties to null resulted in `field "account" may not be empty` error.
2) Setting Account to the QR-IBAN and Reference to null resulted in `QR reference is missing; it is mandatory for payments to a QR-IBAN` error.

I am not sure if I'm missing something or there's a wrong check in the Validator class (line 167):
```csharp
if (isQrBillIban)
{
  if (Bill.ReferenceTypeNoRef == _billOut.ReferenceType && !hasReferenceError) // <-- here
  {
    _validationResult.AddMessage(MessageType.Error, ValidationConstants.FieldReference, ValidationConstants.KeyQrRefMissing);
  }
  else if (Bill.ReferenceTypeCredRef == _billOut.ReferenceType)
  {
    _validationResult.AddMessage(MessageType.Error, ValidationConstants.FieldReference, ValidationConstants.KeyCredRefInvalidUseForQrIban);
  }
}
```

Should the condition rather be `if (Bill.ReferenceTypeQrRef == _billOut.ReferenceType && hasReferenceError)`?

**Comment by manuelbl** [comment]
The way I read the specification (chapter 4.4. in [Swiss Implementation Guidelines for the QR-bill, version 2.2](https://www.six-group.com/dam/download/banking-services/standardization/qr-bill/ig-qr-bill-v2.2-en.pdf) / [Schweizer Implementation Guidelines QR-Rechnung, Version 2.2](https://www.six-group.com/dam/download/banking-services/standardization/qr-bill/ig-qr-bill-v2.2-de.pdf)), a valid account number is needed even if the bill is marked as "DO NOT USE FOR PAYMENT".

If an account is provided, the normal rules apply:

- If the account number is a QR-IBAN, a numeric reference number is required.
- If the account number is a non-QR-IBAN, the reference number is optional. If provided, it must have the RFxxxx format.

The below code produces a valid *DO NOT USE FOR PAYMENT* bill (according to my understanding of the spec):

```csharp
var bill = new Bill
{
    // creditor data
    Account = "CH4431999123000889012",
    Creditor = new Address
    {
        Name = "Robert Schneider AG",
        Street = "Rue du Lac",
        HouseNo = "1268/2/22",
        PostalCode = "2501",
        Town = "Biel",
        CountryCode = "CH"
    },

    // payment data
    Amount = 0,

    // debtor data
    Debtor = new Address
    {
        Name = "Pia-Maria Rutschmann-Schnyder",
        Street = "Grosse Marktgasse",
        HouseNo = "28",
        PostalCode = "9400",
        Town = "Rorschach",
        CountryCode = "CH"
    },

    // more payment data
    Reference = "210000000003139471430009017",
    UnstructuredMessage = "DO NOT USE FOR PAYMENT",

    // output format
    Format = new BillFormat
    {
        Language = Language.DE,
        GraphicsFormat = GraphicsFormat.SVG,
        OutputSize = OutputSize.QrBillOnly
    }
};

// Generate QR bill
byte[] svg = QRBill.Generate(bill);

// Save generated SVG file
const string path = "qrbill.svg";
File.WriteAllBytes(path, svg);
Console.WriteLine($"QR bill saved at {Path.GetFullPath(path)}");

```

**Comment by axelgenus** [comment]
I also just noticed that one of the comments for the reference field says: "The element must not be filled in for the reference type
NON."

**Comment by manuelbl** [comment]
As far as the reference number is concerned, there are 3 options:

1. QR-IBAN and numeric reference (QRR)
2. Non-QR-IBAN and creditor reference (SCOR)
3. Non-QR-IBAN and no reference (NON)

This isn't specific to QR bills. It applies to the Swiss payment system in general (including transactions via SIC, PAIN specification etc.)

There is no special provision for the *DO NOT USE FOR PAYMENT* case. At least I can't see any. Omitting the account number doesn't work either as it is mandatory in the QR bill specification.

Since you obviously want to use a QR-IBAN, you have to specify a numeric QRR reference. I don't see any other option.

It wouldn't help either if this library implemented something that isn't widely accepted in Switzerland. It would successfully generate a QR bill in a grey area. But most QR bill scanners would reject it.
