### ISSUE TITLE
Valid IBAN

### ISSUE THREAD

**Issue by Ogiz** [manuelbl/SwissQRBill.NET#7]
I am trying to create bill with slovenian IBAN and I keep getting error **account_is_ch_li_iban**.
I used this site https://www.iban.com/iban-checker to check my IBAN and it is valid
IBAN that's failing: SI56610000003603509.

Why is this working only for Liechtenstein and Switzerland?

**Comment by manuelbl** [comment]
QR bills have been designed for payments to accounts in Switzerland and Liechtenstein only. Therefore, IBANs are restricated to IBANs from these two countries.

See also: [Swiss Implementation Guidelines QR-bill](https://www.paymentstandards.ch/dam/downloads/ig-qr-bill-en.pdf), chapter 4.3.3, description of field *IBAN*.
