### ISSUE TITLE
Decoding structured bill information

### ISSUE THREAD

**Issue by BEagle1984** [manuelbl/SwissQRBill.NET#8]
The structured bill information is currently being returned as raw string by the `QrBill.DecodeQrCodeText`, do you plan on decoding that as well? Or would you accept a PR (since we would need to implement it ourselves in any case)?

**Comment by manuelbl** [comment]
I haven't dealt with it yet and don't fully understand it. A PR is very welcome.

**Comment by BEagle1984** [comment]
Ok, you’ll get a PR. 👍

**Comment by manuelbl** [comment]
Solved by release 2.3 and #10
