### ISSUE TITLE
Ignoring reference type?

### ISSUE THREAD

**Issue by BEagle1984** [manuelbl/SwissQRBill.NET#9]
`QrCodeText.Decode` deliberately ignores the reference type, why? Could you add it to the returned structure? (...or would you take a PR with that fix into consideration?)

https://github.com/manuelbl/SwissQRBill.NET/blob/master/Generator/QRCodeText.cs#L200

**Comment by manuelbl** [comment]
The focus was more on generating QR bills than decoding them. And for generation there is no need for it as it can be derived from the reference.

But it's a worthwhile addition. So I have added it. You can find it in the master branch (see https://github.com/manuelbl/SwissQRBill.NET/commit/cde1804644a5413db89bfcca8e9bffb1bec8af9a). It's not part of a release yet.

**Comment by BEagle1984** [comment]
Wow, that was quick. Thank you!

**Comment by ChrisBerna** [comment]
Could you please include the `ReferenceType` field in a release?

**Comment by manuelbl** [comment]
I was hoping that the PR for structured information (see #8) would be ready soon and a single release could cover the PR and this addition. But that wasn't the case. So I'll go ahead and release this separately.

Are @BEagle1984 and you working on the same project?

**Comment by ChrisBerna** [comment]
Yes I'm working together with @BEagle1984 at the same project. Regarding the structured billing information, I will try to send you the PR in the next days.

**Comment by manuelbl** [comment]
Release 2.2.4 has been published

**Comment by BEagle1984** [comment]
Thank you for your support @manuelbl!
